# Generated by Django 5.1.2 on 2024-10-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village_chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="multi_chat_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
