# Generated by Django 5.1.2 on 2024-10-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village_chatbot", "0002_conversation_multi_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="user_generated_persona_prompt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
