# Generated by Django 5.1.2 on 2024-11-03 19:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village_chatbot", "0003_persona_user_generated_persona_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="age",
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name="persona",
            name="gender",
            field=models.CharField(default="female", max_length=255),
        ),
        migrations.AddField(
            model_name="persona",
            name="interests",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                default=["cooking", "reading"],
                size=8,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="persona",
            name="location",
            field=models.CharField(default="Oslo, Norway", max_length=255),
        ),
        migrations.AddField(
            model_name="persona",
            name="role",
            field=models.CharField(default="", max_length=255),
        ),
    ]
