# Generated by Django 5.1.2 on 2024-11-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("village_chatbot", "0005_alter_persona_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="persona",
            name="preview",
        ),
    ]
